apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Log and Audit IdAM Frontend App
name: lau-idam-frontend
home: https://github.com/hmcts/lau-idam-frontend
version: 0.0.1
dependencies:
  - name: nodejs
    version: 2.3.8
    repository: '@hmctspublic'
  - name: redis
    version: 10.6.18
    repository: 'https://charts.bitnami.com/bitnami'
    condition: redis.enabled
  - name: idam-pr
    version: 2.2.6
    repository: '@hmctspublic'
    condition: idam-pr.enabled
