---
service:
  name: 'lau-idam-frontend'
environment: 'prod'
useCSRFProtection: true
security:
  referrerPolicy: origin
appInsights:
  instrumentationKey: false
pagination:
  maxRecords: 10000
redis:
  host: 'localhost'
  port: 6379
  password: 'dummy_password'
  useTLS: 'false'
  enabled: false
  secret: 'OVERWRITE_THIS'
  proxy: true
  resave: false
  saveUninitialized: false
  cookie:
    secure: false
    httpOnly: true
    sameSite: 'lax'
services:
  idam-backend:
    enabled: true
    url: 'http://localhost:4550'
    port: 4550
    endpoints:
      logon: '/audit/logon'
  idam:
    enabled: true
    s2sEnabled: true
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    s2sURL: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    s2sSecretLAU: 'AAAAAAAAAAAAAAAA'
    clientID: 'lau'
    clientSecret: 'SECRET'
    callbackURL: 'https://localhost:4001/oauth2/callback'
